# Generated by Django 6.0.3 on 2026-03-27 08:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arte', models.CharField(max_length=200)),
                ('nome_reale', models.CharField(blank=True, max_length=200)),
                ('genere', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('contatto', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['nome_arte'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(max_length=300)),
                ('citta', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=5)),
                ('cap', models.CharField(max_length=5)),
                ('capienza', models.PositiveIntegerField()),
                ('accessibile', models.BooleanField(default=True)),
                ('contatto', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'location',
                'ordering': ['citta', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('navetta', 'Navetta'), ('audio', 'Audio/Tecnico'), ('catering', 'Catering'), ('sicurezza', 'Sicurezza'), ('fotografia', 'Fotografia/Video'), ('altro', 'Altro')], default='altro', max_length=50)),
                ('descrizione', models.TextField(blank=True)),
                ('fornitore', models.CharField(blank=True, max_length=200)),
                ('contatto_fornitore', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('is_organizzatore', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=300)),
                ('descrizione', models.TextField(blank=True)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('pubblicato', 'Pubblicato'), ('annullato', 'Annullato'), ('concluso', 'Concluso')], default='bozza', max_length=20)),
                ('capienza_massima', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizzatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_organizzati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='EventoArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('headliner', 'Headliner'), ('opening', 'Opening Act'), ('ospite', 'Ospite Speciale'), ('dj', 'DJ'), ('musicista', 'Musicista'), ('cantante', 'Cantante'), ('altro', 'Altro')], default='altro', max_length=50)),
                ('cachet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orario_esibizione', models.CharField(blank=True, max_length=10)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventi.artista')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventi.evento')),
            ],
            options={
                'unique_together': {('evento', 'artista')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='artisti',
            field=models.ManyToManyField(blank=True, through='eventi.EventoArtista', to='eventi.artista'),
        ),
        migrations.AddField(
            model_name='evento',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventi', to='eventi.location'),
        ),
        migrations.CreateModel(
            name='EventoServizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventi.evento')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventi.servizio')),
            ],
            options={
                'unique_together': {('evento', 'servizio')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='servizi',
            field=models.ManyToManyField(blank=True, through='eventi.EventoServizio', to='eventi.servizio'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_univoco', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('standard', 'Standard'), ('ridotto', 'Ridotto'), ('omaggio', 'Omaggio'), ('vip', 'VIP'), ('early_bird', 'Early Bird')], default='standard', max_length=20)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stato', models.CharField(choices=[('acquistato', 'Acquistato'), ('annullato', 'Annullato'), ('usato', 'Usato')], default='acquistato', max_length=20)),
                ('data_acquisto', models.DateTimeField(auto_now_add=True)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_acquistati', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='eventi.evento')),
            ],
            options={
                'ordering': ['-data_acquisto'],
            },
        ),
    ]
